name: Submission Testing

on: [ pull_request, workflow_dispatch ]

jobs:
  Test-Submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: eWaterCycle/setup-apptainer@v2.0.0
      with:
        apptainer-version: 1.1.2
    - name: Fetching the apptainer container
      run: apptainer pull https://lamp.ms.wits.ac.za/ml/rail.sif
    - name: Starting the apptainer container
      run: apptainer instance start rail.sif rail
    - name: Run classifyall script
      run: apptainer exec instance://rail python scripts/classifyall.py
